routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
import mysql.connector
from sesh import session, set_session, get_session, db_config, CursorContext
import pdb


server = Blueprint("server", __name__, static_folder="static", template_folder="templates", root_path="/home/ubuntu/flaskapp")       # BLUEPRINT


# DEBUG
#@server.before_request
# def before_request():
#    headers = request.headers
#    app.logger.info(f"Request Headers: {headers}")


@server.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'GET':
        return render_template('home.html')



    return render_template('home.html')   # render the template



@server.route('/log_in', methods=['GET', 'POST'])                              #       LOG_IN
def log_in():

    if request.method == 'POST':                                            # POST method
        user_name = request.form['userName'].strip()                        # username
        password = request.form['passWord'].strip()                         # password

        with CursorContext(**db_config) as connection:            # Connect with wrapper class for context 
            cursor = connection.cursor()                                    # cursor
            query = "SELECT password FROM Users WHERE user_name = %s"       # query database for username and select pw hash
            cursor.execute(query, (user_name,))                             # execute query
            result = cursor.fetchone()                                      # get result
            if result:                                                      # if username exists:
                stored_password_hash = result[0]                            # convert stored_hash[tuple] to [str]
                if check_password_hash(stored_password_hash, password):     # check passwd
                    cursor.close()
                    session['user'] = user_name                             # store session data of user
                    print('login successful')                               # debug 
                    return redirect(url_for('home'))                        # redirect back to home page
                else:
                    print('login unsuccessful')                             # debug
            else:
                print('all code ran')                                       # debug
    return render_template('login.html')                                    # render the template




#   REGISTRATION method 
@server.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':                                                # POST method
        firstName = request.form['firstName'].strip()                           # get first name
        lastName = request.form['lastName'].strip()                             # get last name 
        userName = request.form['userName'].strip()                             # get user name
        e_mail = request.form['e-mail'].strip()                                 # get email
        password1 = request.form['password1'].strip()                           # get password1
        password2 = request.form['password2'].strip()                           # get password2 


        with CursorContext(**db_config) as connection:                     # connect with wrapper class
            cursor = connection.cursor()                                        # cursor


            #           CHECK IF ACCOUNT EXISTS WITH USERNAME AND EMAIL 
            query = "SELECT user_name, email FROM Users WHERE user_name = %s AND email = %s" # query
            cursor.execute(query, (userName, e_mail))   # retrieve username and email
            user = cursor.fetchone()                    # get result
            if user:                                    # if user exists: DENY REGISTRATION
                pass

            #           CHECK IF USERNAME IS TAKEN 
            query = "SELECT user_name FROM Users WHERE user_name = %s" # query
            cursor.execute(query, (userName,))          # execute
            username_taken = cursor.fetchone()          # get result
            if username_taken:                          # if username is taken: PLEASE USE ANOTHER USERNAME
                pass

            #           CHECK IF EMAIL IS IN USE
            query = "SELECT email FROM Users WHERE email = %s"         # query  
            cursor.execute(query, (e_mail,))            # execute
            email_taken = cursor.fetchone()             # get result
            if email_taken:                             # if email is taken: PLEASE USE ANOTHER EMAIL
                pass
            #           INITIATE REGISTRATION AS ALL CHECKS HAVE PASSED
            stored_password_hash = generate_password_hash(password1, 'pbkdf2:sha256', 8) # store input password hash
            query = "INSERT INTO Users (first_name, last_name, user_name, email, password) VALUES (%s, %s, %s, %s, %s)"
            cursor.execute(query, (firstName, lastName, userName, e_mail, stored_password_hash)) # execute query
            connection.commit()                         # commit changes
            cursor.close()                              # close cursor
            session.clear()                             # clear session data
            # session["user"] = userName                  # set session username
            # session["log_status"] = true                # set session log status
            user_data = {
                "user": "userName",
                "log_status": "True"
            }
            return redirect(url_for('home', **user_data))
    return render_template('home.html')                 # render template

#@server.route('/user')                                     #       USER 
# def user():
#    if "user" in session:
#        print(f"the user is {user}")
#    pass



#@server.route('/favicon.ico')
# def favicon():
#    response = app.make_response('')  # Create an empty response
#    response.headers['Content-Type'] = 'image/x-icon'
#    app.logger.info(f"Response headers: {response.headers}")
#    return response

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
                My Flask App 
            {% endblock %}
        </title>
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicon-16x16.png">
        <link rel="shortcut icon" href="/static/img/favicon.ico">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!--
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="manifest" href="/site.webmanifest"> 
        -->

        {% block scripts %}
        {% endblock %}

    </head>

    <body>

         <!-- top nav bar -->
        <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
            <!-- nav bar expanding button-->
            <button class="navbar-toggler" type="button" id="nav-expand-button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
    
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a href="{{ return url_for('server.home') }}" class="nav-link"> Home </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ return url_for('server.log_in') }}" class="nav-link"> Log In </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ return url_for('server.register') }}" class="nav-link"> Sign Up </a>
                    </li>
                </ul>
            </div>
        </nav>

        {% block content %}

        {% endblock %}


        

    </body>


</html>

templates/home.html
{% extends "base.html" %}
{% block title %} Home {% endblock %}

{% block scripts %}
    <link type="text/css" rel="stylesheet" href="../static/css/home_styles.css" />
    <script defer src="../static/js/home_script.js" />
{% endblock %}

{% block content %}
<div class="home-top-container">                                        <!-- landing viewport -->
    <div class="main">                                                  <!-- main container -->
        <div class="user_pamphlet">                                     <!-- pamphlet -->
            <div class="user_grid_item" id="pamphlet_user">{{ user }}</div><!-- pamphlet user grid box -->
            <div class="user_grid_item" id="pamphlet_info">{{ user_info }}</div><!-- pamphlet user_info grid box -->
            <form action="log_out" method="POST" class="user_grid_item" id="pamphlet_logout">   <!---pamphlet-->
                <button type="submit" class="btn btn-primary"> Log Out </button>                <!---log_out--->
            </form>                                                                             <!---grid_box-->
        </div>
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block scripts %}
    <script defer src="../static/js/login_script.js"></script>
{% endblock %}


{% block title %}
    Log In
{% endblock %}
{% block content %}
<div class="login-main-container">
    <form action="log_in" method="POST" id="login_form">
        <ul class="list-group">
            <li class="list-group-item">
                <label for="userName">Username: </label>
                    <input type="text" name="userName" placeholder="Username" id="login_username">
            </li>

            <li class="list-group-item">
                <label for="passWord">Password: </label>
                    <input type="password" name="passWord" placeholder="Password" id="login_password">
            </li>

            <li class="list-group-item">
                <button type="submit" class="btn btn-primary"> Submit </button>
            </li>
        </ul>


    </form>
</div>

{% endblock %}

templates/sign-up.html
{% extends "base.html" %}
{% block title%} Sign-Up {% endblock %}

{% block scripts %}
    <script defer src="../static/js/signup_script.js"></script>
    <link type="text/css" rel="stylesheet" href="../static/css/signup_styles.css" />
{% endblock %}

{% block content %}
<div class="signup-main-container">

    <form action="register" method="POST" id="signup_form">
        <ul class="list-group">   
            <li class="list-group-item">
                <label for="firstName">First Name: </label>
                    <input type="text" name="firstName" placeholder="First Name" id="first_name" />
            </li>

            <li class="list-group-item">
                <label for="lastName">Last Name: </label>
                    <input type="text" name="lastName" placeholder="Last Name" id="last_name" />
            </li>

            <li class="list-group-item">
                <label for="userName">User Name: </label>
                    <input type="text" name="userName" placeholder="User Name" id="user_name" />
            </li>

            <li class="list-group-item">
                <label for="email">E-mail: </label>
                    <input type="email" name="e-mail" placeholder="E-mail" id="email" />
            </li>

            <li class="list-group-item">
                <label for="password1">Password: </label>
                    <input type="password" name="password1" placeholder="Password" id="password_1" />
            </li>

            <div id="password_check_display">
                <ul>
                    
                    <li id="password_check_length">
                        <p><i class="far fa-check-circle" id="len_checkbox"></i>Password must be more than 8 characters</p>
                    </li>

                    <li id="password_check_num">
                        <p><i class="far fa-check-circle" id="num_checkbox"></i>Password must contain at least one number.</p>
                    </li>
                    
                    <li id="password_check_special_char">
                        <p><i class="far fa-check-circle" id="special_char_checkbox"></i>Password must at least one special character <br /> 
                            (&quot;!&quot;,&quot;@&quot;, &quot;#&quot;, &quot;?&quot;, etc.). </p>
                    </li>

                    <li id="password_check_capital_char">
                        <p><i class="far fa-check-circle" id="capital_checkbox"></i>Password must contain at least one capital letter.</p>
                    </li>

                    <li id="password_check_lowercase_char">
                        <p><i class="far fa-check-circle" id="lowercase_checkbox"></i>Password must contain at least one lowercase letter.</p>
                    </li>

                </ul>
            </div>

            <li class="list-group-item">
                <label for="password2">Confirm Password: </label>
                    <input type="password" name="password2" placeholder="Re-enter Password" id="password_2" />
            </li>
            <li class="list-group-item" id="password_match_message">
                <p>Passwords don't match. </p>
            </li>

            <li class="list-group-item">
                <button type="submit" class="btn btn-primary"> Submit </button>
            </li>
        </ul>
    </form>

</div>
{% endblock %}